### ISSUE TITLE
Runtime panic with latest release

### ISSUE THREAD

**Issue by grawlinson** [DRuggeri/nut_exporter#15]
Something has broken in-between 2.2.3 and 2.3.0.

```
$ ./nut_exporter-v2.3.0-linux-amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x708d5b]

goroutine 1 [running]:
github.com/go-kit/log.(*context).Log(0xc0001a8000, 0xc000188100, 0x4, 0x4, 0x2, 0x9e53e0)
        github.com/go-kit/log@v0.2.0/log.go:168 +0x2db
main.main()
        github.com/DRuggeri/nut_exporter/nut_exporter.go:234 +0x5d0
```

**Comment by DRuggeri** [comment]
Yep! Thanks for the report, @grawlinson - I just merged PR #14 that should fix this. I will release now as v2.3.1. Cheers and happy new year!
